### PR TITLE
add dotnet pack args for Package{Name, Version}

### PR DESCRIPTION
**Pull request by johnazariah**
add -p:PackageId to respect the value of the PACKAGE_NAME configuration
add -p:PackageVersion to respect the value of the computed version string

reference: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties

### CODE REVIEW

**Comment by rohith** [comment]
Thanks a bunch for the PR 🎉

I understand what this PR does but the `PackageId` & `PackageVersion` are implicitly taken from the name of the `*nupkg` file that's generated. Is there a special case where you see these won't be present & you wanna be explicit about them?

**Comment by johnazariah** [comment]
Yes

When the name of the package specified as a config parameter is different
to the name of the project file, it didn't seem to pick up the name, nor
did it push out a package to nuget...

I had to make these changes on my fork to get it to work. So I contributed
back.

Feel free to fork my repo and try if you like.

johnazariah/orleans-universal-silo

Thanks much

-John

**Comment by rohith** [comment]
I cannot access your repo as it gives 404 (maybe it's private or something) but I'll try to reproduce the issue on a new repo

**Comment by rohith** [comment]
Closing this as it's become stale

**Pull request closed without merging**
